package com.onenetwork.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

import static com.onenetwork.constant.EndPositionConstant.END_FOURTH_POSITION;
import static com.onenetwork.constant.EndPositionConstant.END_SECOND_POSITION;

@AllArgsConstructor
@Getter
public enum ControlIdentifier {

    E0("E0", END_SECOND_POSITION), E1("E1", END_SECOND_POSITION), TEN("10", END_SECOND_POSITION),
    ELEVEN("11", END_SECOND_POSITION), TWENTY("20", END_SECOND_POSITION),
    SE13("SE13", END_FOURTH_POSITION), TWENTY_ONE("21", END_SECOND_POSITION),
    TWENTY_TWO("22", END_SECOND_POSITION), TWENTY_THREE("23", END_SECOND_POSITION),
    SE16("SE16", END_FOURTH_POSITION), SE17("SE17", END_FOURTH_POSITION),
    THIRTY("30", END_SECOND_POSITION), THIRTY_ONE("31", END_SECOND_POSITION),
    THIRTY_TWO("32", END_SECOND_POSITION), THIRTY_THREE("33", END_SECOND_POSITION),
    THIRTY_FOUR("34", END_SECOND_POSITION), THIRTY_FIVE("35", END_SECOND_POSITION),
    THIRTY_SIX("36", END_SECOND_POSITION), SE20("SE20", END_FOURTH_POSITION),
    SE30("SE30", END_FOURTH_POSITION), SE35("SE35", END_FOURTH_POSITION),
    SE36("SE36", END_FOURTH_POSITION), FORTY("40", END_SECOND_POSITION),
    FORTY_ONE("41", END_SECOND_POSITION), FORTY_TWO("42", END_SECOND_POSITION),
    FORTY_THREE("43", END_SECOND_POSITION), FORTY_FOUR("44", END_SECOND_POSITION),
    FORTY_SEVEN("47", END_SECOND_POSITION), SE50("SE50", END_FOURTH_POSITION),
    SE55("SE55", END_FOURTH_POSITION), SE56("SE56", END_FOURTH_POSITION),
    FIFTY("50", END_SECOND_POSITION), SE61("SE61", END_FOURTH_POSITION),
    OI("OI", END_SECOND_POSITION), FIFTY_ONE("51", END_SECOND_POSITION),
    FIFTY_TWO("52", END_SECOND_POSITION), FIFTY_THREE("53", END_SECOND_POSITION),
    FIFTY_FOUR("54", END_SECOND_POSITION), SIXTY("60", END_SECOND_POSITION),
    SIXTY_ONE("61", END_SECOND_POSITION), SIXTY_TWO("62", END_SECOND_POSITION),
    SIXTY_THREE("63", END_SECOND_POSITION), CW02("CW02", END_FOURTH_POSITION),
    EIGHTY_EIGHT("88", END_SECOND_POSITION), EIGHTY_NINE("89", END_SECOND_POSITION),
    NINETY("90", END_SECOND_POSITION), SO10("SO10", END_FOURTH_POSITION),
    SO20("SO20", END_FOURTH_POSITION), SO30("SO30", END_FOURTH_POSITION),
    SO40("SO40", END_FOURTH_POSITION), SO42("SO42", END_FOURTH_POSITION),
    SO50("SO50", END_FOURTH_POSITION), SO60("SO60", END_FOURTH_POSITION),
    SO70("SO70", END_FOURTH_POSITION), SO71("SO71", END_FOURTH_POSITION),
    SO72("SO72", END_FOURTH_POSITION), SF10("SF10", END_FOURTH_POSITION),
    SF20("SF20", END_FOURTH_POSITION), SF25("SF25", END_FOURTH_POSITION),
    SF30("SF30", END_FOURTH_POSITION), SF31("SF31", END_FOURTH_POSITION),
    SF35("SF35", END_FOURTH_POSITION), SF36("SF36", END_FOURTH_POSITION),
    SE10("SE10", END_FOURTH_POSITION), SE11("SE11", END_FOURTH_POSITION),
    SE15("SE15", END_FOURTH_POSITION), SE40("SE40", END_FOURTH_POSITION),
    SE41("SE41", END_FOURTH_POSITION), SE60("SE60", END_FOURTH_POSITION),
    SE90("SE90", END_FOURTH_POSITION), SF13("SF13", END_FOURTH_POSITION),
    SF15("SF15", END_FOURTH_POSITION), SF40("SF40", END_FOURTH_POSITION),
    SF50("SF50", END_FOURTH_POSITION), SF90("SF90", END_FOURTH_POSITION),
    SA10("SA10", END_FOURTH_POSITION), SA20("SA20", END_FOURTH_POSITION),
    SA30("SA30", END_FOURTH_POSITION), SA50("SA50", END_FOURTH_POSITION),
    N1("N1", END_SECOND_POSITION), N2("N2", END_SECOND_POSITION), N3("N3", END_SECOND_POSITION),
    N4("N4", END_SECOND_POSITION);

    private final String identifier;
    private final int endPosition;
}
